version: '3'
services:
app:
build:
contex: .
dockerfile: dockerfile
container_name: dynaform
port: 
- 8080:80

nginx:
image: nginx:alpine
container_name: nginx-app
volumes:
- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
port:
- 80:80
depends_on: 
- app